name: idiot_online
description: The card game called Idiot in Norwegian

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.3+1
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/heart.svg
    - assets/images/club.svg
    - assets/images/spade.svg
    - assets/images/diamond.svg
